name: CI

on:
  push:
    branches: [Develop]
  pull_request:
    branches: [Develop]

jobs:
  build:
    runs-on: ubuntu-22.04 LTS

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: test

      - name: Build project
        run: npm run build
